
#! Anything written here will be deleted.

from PyQt5 import QtCore, QtGui, QtWidgets
from sys import path
path.append("../tab_widgets")
from csv_tab_code import code

def csv_tab(self):

        self.csv_tab = QtWidgets.QWidget()
        self.csv_tab.setStyleSheet("")
        self.csv_tab.setObjectName("csv_tab")
        self.csv_label = QtWidgets.QLabel(self.csv_tab)
        self.csv_label.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.csv_label.setObjectName("csv_label")
        self.PDFButton = QtWidgets.QPushButton(self.csv_tab)
        self.PDFButton.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.PDFButton.setObjectName("PDFButton")
        self.Selection_label = QtWidgets.QLabel(self.csv_tab)
        self.Selection_label.setGeometry(QtCore.QRect(90, 40, 71, 21))
        self.Selection_label.setObjectName("Selection_label")
        self.Selected_label = QtWidgets.QLabel(self.csv_tab)
        self.Selected_label.setGeometry(QtCore.QRect(160, 40, 921, 21))
        self.Selected_label.setText("")
        self.Selected_label.setObjectName("Selected_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.csv_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 1071, 341))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.csv_h_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.csv_h_layout.setContentsMargins(0, 0, 0, 0)
        self.csv_h_layout.setObjectName("csv_h_layout")
        self.csv_table_1 = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.csv_table_1.setRowCount(11)
        self.csv_table_1.setColumnCount(3)
        self.csv_table_1.setObjectName("csv_table_1")
        self.csv_table_1.horizontalHeader().setVisible(False)
        self.csv_table_1.horizontalHeader().setDefaultSectionSize(85)
        self.csv_table_1.verticalHeader().setVisible(False)
        self.csv_table_1.verticalHeader().setHighlightSections(True)
        self.csv_h_layout.addWidget(self.csv_table_1)
        self.csv_table_2 = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.csv_table_2.setRowCount(11)
        self.csv_table_2.setColumnCount(3)
        self.csv_table_2.setObjectName("csv_table_2")
        self.csv_table_2.horizontalHeader().setVisible(False)
        self.csv_table_2.horizontalHeader().setDefaultSectionSize(85)
        self.csv_table_2.verticalHeader().setVisible(False)
        self.csv_table_2.verticalHeader().setHighlightSections(True)
        self.csv_h_layout.addWidget(self.csv_table_2)
        self.csv_table_3 = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.csv_table_3.setRowCount(11)
        self.csv_table_3.setColumnCount(3)
        self.csv_table_3.setObjectName("csv_table_3")
        self.csv_table_3.horizontalHeader().setVisible(False)
        self.csv_table_3.horizontalHeader().setDefaultSectionSize(85)
        self.csv_table_3.verticalHeader().setVisible(False)
        self.csv_h_layout.addWidget(self.csv_table_3)
        self.csv_table_4 = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.csv_table_4.setRowCount(11)
        self.csv_table_4.setColumnCount(3)
        self.csv_table_4.setObjectName("csv_table_4")
        self.csv_table_4.horizontalHeader().setVisible(False)
        self.csv_table_4.horizontalHeader().setDefaultSectionSize(85)
        self.csv_table_4.verticalHeader().setVisible(False)
        self.csv_h_layout.addWidget(self.csv_table_4)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.csv_tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 1071, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.label_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.label_hlayout.setContentsMargins(0, 0, 0, 0)
        self.label_hlayout.setObjectName("label_hlayout")
        self.csv_name_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.csv_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.csv_name_1.setObjectName("csv_name_1")
        self.label_hlayout.addWidget(self.csv_name_1)
        self.csv_name_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.csv_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.csv_name_2.setObjectName("csv_name_2")
        self.label_hlayout.addWidget(self.csv_name_2)
        self.csv_name_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.csv_name_3.setAlignment(QtCore.Qt.AlignCenter)
        self.csv_name_3.setObjectName("csv_name_3")
        self.label_hlayout.addWidget(self.csv_name_3)
        self.csv_name_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.csv_name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.csv_name_4.setObjectName("csv_name_4")
        self.label_hlayout.addWidget(self.csv_name_4)
        self.tabWidget.addTab(self.csv_tab, "")
        code(self)

def csv_elements(self):
        _translate = QtCore.QCoreApplication.translate
        self.csv_label.setText(_translate("Dialog", "Displaying CSV tables containing mission waypoints."))
        self.PDFButton.setText(_translate("Dialog", "Upload PDF"))
        self.Selection_label.setText(_translate("Dialog", "Selected File:"))
        self.csv_name_1.setText(_translate("Dialog", "Payload"))
        self.csv_name_2.setText(_translate("Dialog", "Table_0"))
        self.csv_name_3.setText(_translate("Dialog", "Table_1"))
        self.csv_name_4.setText(_translate("Dialog", "Table_2"))
