# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editable_menu_tabs.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from csv_tab import csv_tab, csv_elements
from mission_tab import mission_tab, mission_elements
from camera_tab import camera_tab, camera_elements
from parameter_tab import parameter_tab, parameter_elements

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 500)
        Dialog.setStyleSheet("QDialog {\n"
        "background-color: grey;\n"
        "}\n"
        "\n"
        "")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1100, 471))
        self.tabWidget.setStyleSheet("QWidget {\n"
        "background-color: lightgrey;\n"
        "}")
        self.tabWidget.setObjectName("tabWidget")
        
        mission_tab(self)

        csv_tab(self)

        parameter_tab(self)

        camera_tab(self)

        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setGeometry(QtCore.QRect(1030, 470, 71, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.raise_()
        self.tabWidget.raise_()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "RobEn_GUI_Utility"))
        mission_elements(self)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mission_tab), _translate("Dialog", "Missions"))
        csv_elements(self)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.csv_tab), _translate("Dialog", "CSV"))
        parameter_elements(self)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.parameter_tab), _translate("Dialog", "Parameters"))
        camera_elements(self)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.camera_tab), _translate("Dialog", "Camera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
